import { PropertyNameInputs } from "../types";

export const defaultPropertyValues: PropertyNameInputs = {
  uid: "",
  prop_id: "",
  video: "",
  images: [],
  existing_images: [],
  price: "",
  facilities: [],
  beds_count: "",
  bathrooms_count: "",
  sqft: "",
  category_id: "",
  maps_url: "",
  security_deposit: "",
  government_id: "",
  city_en: "",
  city_ar: "",
  title_en: "",
  title_ar: "",
  compound_en: "",
  compound_ar: "",
  address_en: "",
  address_ar: "",
  floor_en: "",
  floor_ar: "",
  guest_count: "",
  min_days: "",
  max_days: "",
  period: "",
  description_en: "",
  description_ar: "",
  guest_rules_en: "",
  guest_rules_ar: "",
  cancellation_policy_id: "",
};
